version: '3.8'

services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly
    ports:
      - "6379:6379"
    volumes:
      - ./docker_volumes/dragonfly_data:/data
    restart: unless-stopped
    environment:
      - DEFAULT_MAX_MEMORY=1GB  

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./docker_volumes/mongo_data:/data/db
      - ./docker_volumes/mongo_config:/data/configdb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}


    restart: unless-stopped

  backend_orm:
    build:
      context: ./app/backend/ORM
    container_name: backend_orm
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI_CHILL}
    depends_on:
      - dragonfly
      - mongodb

