[project]
name = "orm"
version = "0.1.0"
description = "service for IO operations"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aioredis>=2.0.1",
    "fastapi>=0.116.1",
    "motor>=3.7.1",
    "uvicorn>=0.35.0",
]
